# Generated by Django 3.1.1 on 2020-11-20 20:24

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel (
            name='Client',
            fields=[
                ('id', models.AutoField (auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField (max_length=50)),
                ('login', models.CharField (max_length=50)),
                ('password', models.CharField (max_length=50)),
                ('pol', models.CharField (max_length=50)),
                ('age', models.IntegerField ( )),
                ('mail', models.EmailField (max_length=254)),
            ],
        ),
    ]
