# Generated by Django 3.1.1 on 2020-11-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
    ]
